const packData = [
  {
    packName: "Pack Section 1",
    packItems: [
      {
        name: "Option 1",
        sku: "100001",
        price: 999,
        icon: "Apple",
        featured: false,
      },
      {
        name: "Option 2",
        sku: "100002",
        price: 1999,
        icon: "Bean",
        featured: false,
      },
      {
        name: "Option 3",
        sku: "100003",
        price: 2999,
        icon: "Beef",
        featured: false,
      },
      {
        name: "Option 4",
        sku: "100004",
        price: 3999,
        icon: "Banana",
        featured: false,
      },
      {
        name: "Option 5",
        sku: "100005",
        price: 4999,
        icon: "Cake",
        featured: false,
      },
      {
        name: "Option 6",
        sku: "100006",
        price: 5999,
        icon: "Candy",
        featured: false,
      },
      {
        name: "Option 7",
        sku: "100007",
        price: 6999,
        icon: "Carrot",
        featured: false,
      },
      {
        name: "Option 8",
        sku: "100008",
        price: 7999,
        icon: "Cherry",
        featured: false,
      },
    ],
  },
  {
    packName: "Pack Section 2",
    packItems: [
      {
        name: "Option 1",
        sku: "100009",
        price: 999,
        icon: "Coffee",
        featured: false,
      },
      {
        name: "Option 2",
        sku: "100010",
        price: 1999,
        icon: "Cookie",
        featured: false,
      },
      {
        name: "Option 3",
        sku: "100011",
        price: 2999,
        icon: "Donut",
        featured: false,
      },
      {
        name: "Option 4",
        sku: "100012",
        price: 3999,
        icon: "Egg",
        featured: false,
      },
      {
        name: "Option 5",
        sku: "100013",
        price: 4999,
        icon: "Fish",
        featured: true,
      },
      {
        name: "Option 6",
        sku: "100014",
        price: 5999,
        icon: "Grape",
        featured: true,
      },
    ],
  },
  {
    packName: "Pack Section 3",
    packItems: [
      {
        name: "Option 1",
        sku: "100015",
        price: 999,
        icon: "Hop",
        featured: false,
      },
      {
        name: "Option 2",
        sku: "100016",
        price: 1999,
        icon: "Lollipop",
        featured: false,
      },
      {
        name: "Option 3",
        sku: "100017",
        price: 2999,
        icon: "Nut",
        featured: false,
      },
      {
        name: "Option 4",
        sku: "100018",
        price: 3999,
        icon: "Milk",
        featured: false,
      },
      {
        name: "Option 5",
        sku: "100019",
        price: 4999,
        icon: "Pizza",
        featured: true,
      },
      {
        name: "Option 6",
        sku: "100020",
        price: 5999,
        icon: "Popcorn",
        featured: true,
      },
    ],
  },
];

export default packData;
